spring:
  application:
    name: xj-rule
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/rule?useUnicode=true&characterEncoding=UTF-8
    username: root
    hikari:
      autoCommit: true
      maximumPoolSize: 500
      maxLifetime: 1800000
      idleTimeout: 60000
      minimumIdle: 10
      initializationFailTimeout: 10000
      connectionTimeout: 3000
      validationTimeout: 5000
      connectionTestQuery: SELECT 1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        show_sql: false
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 500
          batch_versioned_data: true

    hibernate:
      ddl-auto: update
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  freemarker:
    cache: false
    charset: UTF-8
    checkTemplateLocation: true
    content-type: text/html
    enabled: true
    number_format: '''0.##'' '
    request-context-attribute: req
    suffix: .ftl
    template-loader-path: classpath:/templates/

rule:
  akkaGlobalWorkerPoolInitSize: 100
  akkaGlobalWorkerPoolMaxSize: 2000
  akkaDefaultExecuteTimeoutSeconds: 600
  attachmentPath: F://xj-rule/attachment